apiVersion: v1
kind: Service
metadata:
  name: ms-payment-service
  namespace: tech-challenge
  labels:
    app: ms-payment
spec:
  selector:
    app: ms-payment
  type: LoadBalancer
  ports:
    - name: http
      port: 8888
      targetPort: 80
      protocol: TCP